import { createRouter as createTanStackRouter } from "@tanstack/react-router";
// @ts-expect-error routeTree.gen is auto-generated by TanStack Start on first dev run
import { routeTree } from "./routeTree.gen";

export function createRouter() {
  return createTanStackRouter({
    routeTree,
    scrollRestoration: true,
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof createRouter>;
  }
}
